ALTER TABLE dbprojetotabajara.Students
ADD COLUMN RG VARCHAR(20),
ADD COLUMN CPF VARCHAR(20),
ADD COLUMN CellPhone VARCHAR(20),
ADD COLUMN SpecialNeeds VARCHAR(255),
ADD COLUMN Email VARCHAR(30),
ADD COLUMN Gender VARCHAR(30),
ADD COLUMN EducationDegree VARCHAR(50),
ADD COLUMN School VARCHAR(255),
ADD COLUMN SchoolShift VARCHAR(30),
ADD COLUMN BloodType VARCHAR(15),
ADD COLUMN Height VARCHAR(15),
ADD COLUMN Weight VARCHAR(15),
ADD COLUMN StartDate DATETIME;
