version: '3.9'

services:
  projetoTabajaraApi:
    image: douglasrfdamasceno/projetotabajara:1.0
    container_name: projetoTabajaraApi
    networks:
      - projetotabajara-bridge
    build:
      context: .
    ports:
      - 8080:80
    environment:
      - SYMMETRIC_SECURITY_KEY=${SYMMETRIC_SECURITY_KEY}
      - HOST_DB=${HOST_DB}
      - PORT_DB=${PORT_DB}
      - USER_DB=${USER_DB}
      - PASS_DB=${PASS_DB}
      - DATABASE_DB=${DATABASE_DB}
    depends_on:
      - mysql

networks:
  projetotabajara-bridge:
    driver: bridge
