version: '3.9'

services:
  mysql:
    image: mysql:5.7
    networks:
      - projetotabajara-bridge
    ports:
      - 3307:3307
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-db:/var/lib/mysql

  projetoTabajaraApi:
    image: projetotabajara
    container_name: ProjetoTabajaraApi
    networks:
      - projetotabajara-bridge
    build:
      context: .
    ports:
      - 8080:80
    environment:
      - SYMMETRIC_SECURITY_KEY=${SYMMETRIC_SECURITY_KEY}
      - DB_CONNECTION=${DB_CONNECTION}
    depends_on:
      - mysql

networks:
  projetotabajara-bridge:
    driver: bridge

volumes:
  mysql-db:
