version: '3.4'

services:
  projetoTabajaraApi-app:
    image: projetotabajara
    container_name: ProjetoTabajaraApi
    build:
      context: .
    ports:
      - 8080:80
    env_file:
      - .env

