apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-projeto-tabajara-statefulset
spec:
  selector:
    matchLabels:
      app: db-projeto-tabajara
  serviceName: svc-db-projeto-deployment
  replicas: 1
  template:
    metadata:
      name: db-projeto-tabajara
      labels:
        app: db-projeto-tabajara
    spec:
      containers:
      - name: db-projeto-tabajara-container
        image: mysql:5.7
        ports:
        - containerPort: 3306
        envFrom:
            - configMapRef:
                name: db-config-map
        volumeMounts:
          - name: mysql-db-volume
            mountPath: /var/lib/mysql
    volumes:
      - name: mysql-db-volume
        persistentVolumeClaim:
          claimName: mysql-db-pvc
